apiVersion: v1
kind: Secret
metadata:
  name: {{ include "author.fullname" . }}-secret
type: Opaque
data:
  username: {{ .Values.secret.username }}
  password: {{ .Values.secret.password }}
stringData:
  username: root
  password: password