apiVersion: v1
kind: Secret
metadata:
  name: {{ include "author.fullname" . }}-secret
type: Opaque
data:
  username: {{ .Values.secret.username }}
  password: {{ .Values.secret.password }}
# 아래와 같이 값을 적어주거나 deployment.yaml의 DB 환경변수 값에 직접 적어둬도 되지만 보안에 취약
# stringData:
#   username: root
#   password: password