apiVersion: v1
kind: Service
metadata:
  name: {{ include "author.fullname" . }}-service
  labels:
    {{- include "author.labels" . | nindent 4 }}
    {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "author.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}